"""Pydantic models for Gemini-generated recipe data."""

from pydantic import BaseModel, Field


class InstructionStep(BaseModel):
    """A single step in a recipe's instructions."""

    number: int
    step: str


class RecipeDetail(BaseModel):
    """A complete recipe generated by Gemini."""

    title: str
    ready_in_minutes: int = 0
    servings: int = 0
    summary: str = ""
    ingredients_used: list[str] = Field(default_factory=list)
    ingredients_extra: list[str] = Field(default_factory=list)
    steps: list[InstructionStep] = Field(default_factory=list)
